// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class FullEmployeeDetailsGetByidResult
    {
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string FathersOccupation { get; set; }
        public string MothersOccupation { get; set; }
        public string DateOfBirthCertificate { get; set; }
        public string DateOfBirthOrginal { get; set; }
        public string PlaceOfBirth { get; set; }
        public string NationalIDNO { get; set; }
        public string BirthCertificateNo { get; set; }
        public string NoOfSon { get; set; }
        public string NoOfDaughters { get; set; }
        public string Telephone { get; set; }
        public string TINNo { get; set; }
        public string ExtraCurricularActivities { get; set; }
        public string PersonalEmail { get; set; }
        public string CardNo { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string BloodGroup { get; set; }
        public string Nationality { get; set; }
        public string Religion { get; set; }
        public string PassportNo { get; set; }
        public string PassportExpiryDate { get; set; }
        public string DrivingLicenseNo { get; set; }
        public string DrivingLicenseExpiryDate { get; set; }
        public string WorkPermitNo { get; set; }
        public string WorkPermitType { get; set; }
        public DateTime WpEffectiveDate { get; set; }
        public DateTime WpExpireDate { get; set; }
        public string BranchName { get; set; }
        public string DepartmentName { get; set; }
        public string DesignationName { get; set; }
        public string EmployeeType { get; set; }
        public string EmploymentNature { get; set; }
        public string GradeNo { get; set; }
        [Column("GrossSalary", TypeName = "decimal(18,2)")]
        public decimal GrossSalary { get; set; }
        public string ShiftName { get; set; }
        public string ModeOfPayment { get; set; }
        public string ImmediateSupervisor { get; set; }
        public string HeadOfDepartment { get; set; }
        public string OfficialPhone { get; set; }
        public string OfficialEmail { get; set; }
        public string AppointmentLetterDate { get; set; }
        public string JoiningDate { get; set; }
        public string ProbationPeriod { get; set; }
        public string ProbationEndDate { get; set; }
        public string ConfirmationDate { get; set; }
        public string ContractEndDate { get; set; }
        public string ServiceLength { get; set; }
        public string LeavingDate { get; set; }
        public string PresentAddress { get; set; }
        public string ParmanentAddress { get; set; }
        public string EmContactName1 { get; set; }
        public string EmContactRelation1 { get; set; }
        public string EmContactMobile1 { get; set; }
        public string EmContactPhone1 { get; set; }
        public string EmContactEmail { get; set; }
        public string EmContactName2 { get; set; }
        public string EmContactRelation2 { get; set; }
        public string EmContactMobile2 { get; set; }
        public string EmContactPhone2 { get; set; }
        public string EmContactEmai2 { get; set; }
        public byte[] Photo { get; set; }
        public byte[] DigitalSignature { get; set; }
    }
}
